Refs #19 - Add the possibility to precise the field used for ordering
novafloss/django-chunkator pull request #20
Opened 2017-06-30 09:51 UTC by zebuline

2017-06-30 09:56 UTC, brunobord requested changes
small changes, it may not be possible to enlarge the scope to unique fields.

2017-06-30 09:56 UTC, brunobord commented on demo/demo_chunkator/tests.py
> +        Profile.objects.create(user=user, avatar='wonderfull')
wonderful

2017-06-30 09:56 UTC, brunobord commented on chunkator/__init__.py
> +        if not field.primary_key:
works only for primary keys... I'm fine with it, but I'd rather also allow if the field has ``unique=True`` ; not all unique indexes are primary keys.

2017-06-30 09:59 UTC, zebuline commented on chunkator/__init__.py
> +        if not field.primary_key:
may be later ? :)

2017-06-30 11:59 UTC, zebuline commented on chunkator/__init__.py
> +        if not field.primary_key:
As discussed IRL: it is possible to have a field with `unique=True` and `null=True`. So we chosed not to support unique fields which are not primary keys.

2017-06-30 11:59 UTC, zebuline commented
@brunobord OPM ?

2017-06-30 13:10 UTC, zebuline commented
Don't move ! I simplified the PR :)

2017-06-30 15:33 UTC, brunobord requested changes
didn't you forget to clean something up?

2017-06-30 15:33 UTC, brunobord commented on chunkator/__init__.py
> +class NoPkException(Exception):
what has happened to this exception? looks like it's not used anymore... :/

2017-07-03 07:20 UTC, zebuline commented on chunkator/__init__.py
> +class NoPkException(Exception):
oops, thx :)

2017-07-03 08:07 UTC, brunobord approved these changes

2017-07-03 08:08 UTC, merged

2017-07-03 08:08 UTC, brunobord commented
now you can rebase #21

2017-07-03 08:21 UTC, zebuline commented
\o/